// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAt-YfKlQ-F_TRp6x7V_PyNkqeVEdiAFtQ',
    appId: '1:115613370863:web:667bd49c9051287d8b4e1a',
    messagingSenderId: '115613370863',
    projectId: 'sigara-80178',
    authDomain: 'sigara-80178.firebaseapp.com',
    storageBucket: 'sigara-80178.firebasestorage.app',
    measurementId: 'G-80YJ18K6S4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCK7cATJmgkYGU-xlMlJXHhRFL0QO8-9No',
    appId: '1:115613370863:android:eb00386a0c40b5578b4e1a',
    messagingSenderId: '115613370863',
    projectId: 'sigara-80178',
    storageBucket: 'sigara-80178.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-Ds-l0UV4BE3pinjgbB5kia3oCvuOXsg',
    appId: '1:115613370863:ios:d19f32ec52aa00678b4e1a',
    messagingSenderId: '115613370863',
    projectId: 'sigara-80178',
    storageBucket: 'sigara-80178.firebasestorage.app',
    iosBundleId: 'com.cervus.sigara',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-Ds-l0UV4BE3pinjgbB5kia3oCvuOXsg',
    appId: '1:115613370863:ios:d19f32ec52aa00678b4e1a',
    messagingSenderId: '115613370863',
    projectId: 'sigara-80178',
    storageBucket: 'sigara-80178.firebasestorage.app',
    iosBundleId: 'com.cervus.sigara',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAt-YfKlQ-F_TRp6x7V_PyNkqeVEdiAFtQ',
    appId: '1:115613370863:web:4c248f65ea97e7398b4e1a',
    messagingSenderId: '115613370863',
    projectId: 'sigara-80178',
    authDomain: 'sigara-80178.firebaseapp.com',
    storageBucket: 'sigara-80178.firebasestorage.app',
    measurementId: 'G-HVEVT9K7Q3',
  );
}
